# Generated by Django 2.2 on 2019-08-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('slug', 'course')},
        ),
    ]
