# Generated by Django 2.2 on 2019-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('main', 'Main'), ('sec', 'Secondary')], default='main', max_length=120),
        ),
    ]
