# Generated by Django 2.2 on 2019-08-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
    ]
