# Generated by Django 2.2 on 2019-08-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_mycourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
