# Generated by Django 2.2.1 on 2019-10-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191001_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=240, unique=True, verbose_name='Post title'),
        ),
    ]
