# Generated by Django 2.2.1 on 2019-10-01 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191001_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 1, 11, 54, 47, 641498, tzinfo=utc)),
        ),
    ]
